formatting:
  FinalNewline:
    active: false
  Indentation:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  MagicNumber:
    active: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - 'Composable'
